database:
    app:
        name: budgetapp
        conn:
            host: mybudgetapp.cnabm39v53bz.ap-southeast-2.rds.amazonaws.com
            port: 5432
            user: budgetapp
            password: budgetapp
            stale_timeout: 300
            max_connections: 100

cors:
    allowed_origins:
        - 'http://localhost:4000'
